### ISSUE TITLE
Unnecessary recursive calls for nested boxes 

### ISSUE THREAD

**Issue by gyk** [sile/mse_fmp4#1]
In the default implementation of `Mp4Box`, one `Mp4Box::write_box` call invokes calling `write_box_payload` twice (one directly, the other by `box_size`). In the case of nested boxes, e.g., `track.mdia_box.minf_box.stbl_box.stsd_box.sample_entries`, it can cause an explosion of recursive calls of `write_box_payload`.

This can be inspected by putting a `println!` line at the beginning of `AvcConfigurationBox`/`Mpeg4EsDescriptorBox`'s `write_box_payload` method.

**Comment by sile** [comment]
I added the required `Mp4Box::box_paload_size` method and implementations of it for solving this problem (commit: https://github.com/sile/mse_fmp4/commit/1f4e41e60becef55954cdc8710f3fa37b5ed7ef9).
By this modification, the number of  `Mp4Box::write_box_payload`  calls has been minimized in most `Mp4Box` implemntations.

**Comment by gyk** [comment]
Actually I thought of a solution that makes `Mp4Box::write_box_payload(&self)` return `Result<Vec<u8>>` and takes `payload.len()` as `box_size` in `Mp4Box::write_box`. Or equivalently, let `write_box` return the `Vec` so the `size` field can be randomly accessed. Your approach is a little harder to implement but can avoid excessive memory copying. Thanks so much for the fix!
