### ISSUE TITLE
How to convert avc1 and m4a metadata in rtmp to fmp4?

### ISSUE THREAD

**Issue by mycrl** [sile/mse_fmp4#3]
I am writing a rust rtmp live server.
I checked the documentation for this project and found that there are a lot of apis I don't understand.
If you are convenient, can you add a more detailed use case or can you answer this question?
thank you very much!

**Comment by sile** [comment]
I don't have an example for RTMP.
Instead, `mse_fmp4` contains a function that converts MPEG2-TS (a container format used by HLS) packets to fMP4 ([mpeg2_ts.rs#L22](https://github.com/sile/mse_fmp4/blob/master/src/mpeg2_ts.rs#L22)). It may be possible to reuse the function by replacing [read_avc_aac_stream](https://github.com/sile/mse_fmp4/blob/master/src/mpeg2_ts.rs#L204) function to one for RTMP.

**Comment by mycrl** [comment]
> 我没有RTMP的例子。
> 相反，它`mse_fmp4`包含一个将MPEG2-TS（HLS使用的容器格式）数据包转换为fMP4（[mpeg2_ts.rs＃L22](https://github.com/sile/mse_fmp4/blob/master/src/mpeg2_ts.rs#L22)）的[函数](https://github.com/sile/mse_fmp4/blob/master/src/mpeg2_ts.rs#L22)。可以通过将[read_avc_aac_stream](https://github.com/sile/mse_fmp4/blob/master/src/mpeg2_ts.rs#L204)函数替换为RTMP 的函数来重用该函数。

ok! thank you very much!
