### ISSUE TITLE
Separate audio and video segment output files

### ISSUE THREAD

**Issue by yayayayayayayayayayayaya** [sile/mse_fmp4#6]
Hi, I just came across this project and it looks great! I looked at the example and saw that the segments contain both the audio and the video tracks. How would it be possible to create separate segments for audio and video? Thanks and best regards, Ya

**Comment by sile** [comment]
Hi, 
Unfortunately, there is no such built-in feature to enable that.
To create separate segments for audio and video, you need to implement a variant of [`mpeg2_ts::to_fmp4`](https://github.com/sile/mse_fmp4/blob/master/src/mpeg2_ts.rs#L24) on your own.

**Comment by yayayayayayayayayayayaya** [comment]
Hi @sile, I see, thanks for your quick response!
